'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="CM")>  _
Partial Public Class DailyEmployeeShiftViewDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.CashManagement.My.MySettings.Default.CMConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property DailyEmployeeShiftViews() As System.Data.Linq.Table(Of DailyEmployeeShiftView)
		Get
			Return Me.GetTable(Of DailyEmployeeShiftView)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.DailyEmployeeShiftView")>  _
Partial Public Class DailyEmployeeShiftView
	
	Private _RecordId As Integer
	
	Private _DailyShiftHeaderRecordId As Integer
	
	Private _Date As Date
	
	Private _StartTime As Date
	
	Private _EndTime As Date
	
	Private _Hours As System.Nullable(Of System.TimeSpan)
	
	Private _ThisShiftEmployeeRecordId As Integer
	
	Private _EmployeeRecordId As Integer
	
	Private _DefaultShiftRecordId As Integer
	
	Private _EmployeeStartTime As Date
	
	Private _EmployeeEndTime As Date
	
	Private _EmployeeHours As System.Nullable(Of System.TimeSpan)
	
	Private _Memo As String
	
	Private _ClockStartTime As Date
	
	Private _ClockEndTime As Date
	
	Private _ShiftDescription As String
	
	Private _EmployeeName As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecordId", DbType:="Int NOT NULL")>  _
	Public Property RecordId() As Integer
		Get
			Return Me._RecordId
		End Get
		Set
			If ((Me._RecordId = value)  _
						= false) Then
				Me._RecordId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DailyShiftHeaderRecordId", DbType:="Int NOT NULL")>  _
	Public Property DailyShiftHeaderRecordId() As Integer
		Get
			Return Me._DailyShiftHeaderRecordId
		End Get
		Set
			If ((Me._DailyShiftHeaderRecordId = value)  _
						= false) Then
				Me._DailyShiftHeaderRecordId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="Date", Storage:="_Date", DbType:="Date NOT NULL")>  _
	Public Property [Date]() As Date
		Get
			Return Me._Date
		End Get
		Set
			If ((Me._Date = value)  _
						= false) Then
				Me._Date = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StartTime", DbType:="DateTime NOT NULL")>  _
	Public Property StartTime() As Date
		Get
			Return Me._StartTime
		End Get
		Set
			If ((Me._StartTime = value)  _
						= false) Then
				Me._StartTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EndTime", DbType:="DateTime NOT NULL")>  _
	Public Property EndTime() As Date
		Get
			Return Me._EndTime
		End Get
		Set
			If ((Me._EndTime = value)  _
						= false) Then
				Me._EndTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Hours", DbType:="Time")>  _
	Public Property Hours() As System.Nullable(Of System.TimeSpan)
		Get
			Return Me._Hours
		End Get
		Set
			If (Me._Hours.Equals(value) = false) Then
				Me._Hours = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ThisShiftEmployeeRecordId", DbType:="Int NOT NULL")>  _
	Public Property ThisShiftEmployeeRecordId() As Integer
		Get
			Return Me._ThisShiftEmployeeRecordId
		End Get
		Set
			If ((Me._ThisShiftEmployeeRecordId = value)  _
						= false) Then
				Me._ThisShiftEmployeeRecordId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeRecordId", DbType:="Int NOT NULL")>  _
	Public Property EmployeeRecordId() As Integer
		Get
			Return Me._EmployeeRecordId
		End Get
		Set
			If ((Me._EmployeeRecordId = value)  _
						= false) Then
				Me._EmployeeRecordId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DefaultShiftRecordId", DbType:="Int NOT NULL")>  _
	Public Property DefaultShiftRecordId() As Integer
		Get
			Return Me._DefaultShiftRecordId
		End Get
		Set
			If ((Me._DefaultShiftRecordId = value)  _
						= false) Then
				Me._DefaultShiftRecordId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeStartTime", DbType:="DateTime NOT NULL")>  _
	Public Property EmployeeStartTime() As Date
		Get
			Return Me._EmployeeStartTime
		End Get
		Set
			If ((Me._EmployeeStartTime = value)  _
						= false) Then
				Me._EmployeeStartTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeEndTime", DbType:="DateTime NOT NULL")>  _
	Public Property EmployeeEndTime() As Date
		Get
			Return Me._EmployeeEndTime
		End Get
		Set
			If ((Me._EmployeeEndTime = value)  _
						= false) Then
				Me._EmployeeEndTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeHours", DbType:="Time")>  _
	Public Property EmployeeHours() As System.Nullable(Of System.TimeSpan)
		Get
			Return Me._EmployeeHours
		End Get
		Set
			If (Me._EmployeeHours.Equals(value) = false) Then
				Me._EmployeeHours = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Memo", DbType:="VarChar(255)")>  _
	Public Property Memo() As String
		Get
			Return Me._Memo
		End Get
		Set
			If (String.Equals(Me._Memo, value) = false) Then
				Me._Memo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClockStartTime", DbType:="DateTime NOT NULL")>  _
	Public Property ClockStartTime() As Date
		Get
			Return Me._ClockStartTime
		End Get
		Set
			If ((Me._ClockStartTime = value)  _
						= false) Then
				Me._ClockStartTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClockEndTime", DbType:="DateTime NOT NULL")>  _
	Public Property ClockEndTime() As Date
		Get
			Return Me._ClockEndTime
		End Get
		Set
			If ((Me._ClockEndTime = value)  _
						= false) Then
				Me._ClockEndTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShiftDescription", DbType:="VarChar(30)")>  _
	Public Property ShiftDescription() As String
		Get
			Return Me._ShiftDescription
		End Get
		Set
			If (String.Equals(Me._ShiftDescription, value) = false) Then
				Me._ShiftDescription = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeName", DbType:="VarChar(51)")>  _
	Public Property EmployeeName() As String
		Get
			Return Me._EmployeeName
		End Get
		Set
			If (String.Equals(Me._EmployeeName, value) = false) Then
				Me._EmployeeName = value
			End If
		End Set
	End Property
End Class
