<?xml version="1.0" encoding="utf-8"?><Database Name="CM" Class="InventoryViewDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\SQLEXPRESS;Initial Catalog=CM;Integrated Security=True;MultipleActiveResultSets=True" SettingsObjectName="CashManagement.My.MySettings" SettingsPropertyName="CMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.InventoryView" Member="InventoryViews">
    <Type Name="InventoryView">
      <Column Name="RecordId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CostPrice" Type="System.Decimal" DbType="Decimal(13,2) NOT NULL" CanBeNull="false" />
      <Column Name="SellingPrice" Type="System.Decimal" DbType="Decimal(13,2) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SupplierDescription" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="InactiveInventory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InactiveInventoryDescription" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
    </Type>
  </Table>
</Database>