'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="CM")>  _
Partial Public Class LeaveTakenViewDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.CashManagement.My.MySettings.Default.CMConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property LeaveTakenViews() As System.Data.Linq.Table(Of LeaveTakenView)
		Get
			Return Me.GetTable(Of LeaveTakenView)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.LeaveTakenView")>  _
Partial Public Class LeaveTakenView
	
	Private _RecordId As Integer
	
	Private _StartDate As Date
	
	Private _EndDate As Date
	
	Private _Days As System.Nullable(Of Integer)
	
	Private _LeaveType As String
	
	Private _LeaveTakenEmployeeRecordId As Integer
	
	Private _ThisLeaveTakenEmployee As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecordId", DbType:="Int NOT NULL")>  _
	Public Property RecordId() As Integer
		Get
			Return Me._RecordId
		End Get
		Set
			If ((Me._RecordId = value)  _
						= false) Then
				Me._RecordId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StartDate", DbType:="Date NOT NULL")>  _
	Public Property StartDate() As Date
		Get
			Return Me._StartDate
		End Get
		Set
			If ((Me._StartDate = value)  _
						= false) Then
				Me._StartDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EndDate", DbType:="Date NOT NULL")>  _
	Public Property EndDate() As Date
		Get
			Return Me._EndDate
		End Get
		Set
			If ((Me._EndDate = value)  _
						= false) Then
				Me._EndDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Days", DbType:="Int")>  _
	Public Property Days() As System.Nullable(Of Integer)
		Get
			Return Me._Days
		End Get
		Set
			If (Me._Days.Equals(value) = false) Then
				Me._Days = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LeaveType", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property LeaveType() As String
		Get
			Return Me._LeaveType
		End Get
		Set
			If (String.Equals(Me._LeaveType, value) = false) Then
				Me._LeaveType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LeaveTakenEmployeeRecordId", DbType:="Int NOT NULL")>  _
	Public Property LeaveTakenEmployeeRecordId() As Integer
		Get
			Return Me._LeaveTakenEmployeeRecordId
		End Get
		Set
			If ((Me._LeaveTakenEmployeeRecordId = value)  _
						= false) Then
				Me._LeaveTakenEmployeeRecordId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ThisLeaveTakenEmployee", DbType:="VarChar(51)")>  _
	Public Property ThisLeaveTakenEmployee() As String
		Get
			Return Me._ThisLeaveTakenEmployee
		End Get
		Set
			If (String.Equals(Me._ThisLeaveTakenEmployee, value) = false) Then
				Me._ThisLeaveTakenEmployee = value
			End If
		End Set
	End Property
End Class
