'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="CM")>  _
Partial Public Class SalesViewDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.CashManagement.My.MySettings.Default.CMConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property SalesViews() As System.Data.Linq.Table(Of SalesView)
		Get
			Return Me.GetTable(Of SalesView)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SalesView")>  _
Partial Public Class SalesView
	
	Private _RecordId As Integer
	
	Private _Date As Date
	
	Private _GrossSales As Decimal
	
	Private _Payout As Decimal
	
	Private _TurnoverCash As Decimal
	
	Private _TurnoverCreditCard As Decimal
	
	Private _TurnoverOther As Decimal
	
	Private _OverbakePercent100 As Decimal
	
	Private _WastagePercent100 As Decimal
	
	Private _DamagePercent100 As Decimal
	
	Private _StaffPercent100 As Decimal
	
	Private _DiscountPercent20 As Decimal
	
	Private _SamplePercent100 As Decimal
	
	Private _StockVarianceValue As Decimal
	
	Private _EmployeeName As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecordId", DbType:="Int NOT NULL")>  _
	Public Property RecordId() As Integer
		Get
			Return Me._RecordId
		End Get
		Set
			If ((Me._RecordId = value)  _
						= false) Then
				Me._RecordId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="Date", Storage:="_Date", DbType:="Date NOT NULL")>  _
	Public Property [Date]() As Date
		Get
			Return Me._Date
		End Get
		Set
			If ((Me._Date = value)  _
						= false) Then
				Me._Date = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GrossSales", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property GrossSales() As Decimal
		Get
			Return Me._GrossSales
		End Get
		Set
			If ((Me._GrossSales = value)  _
						= false) Then
				Me._GrossSales = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Payout", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property Payout() As Decimal
		Get
			Return Me._Payout
		End Get
		Set
			If ((Me._Payout = value)  _
						= false) Then
				Me._Payout = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TurnoverCash", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property TurnoverCash() As Decimal
		Get
			Return Me._TurnoverCash
		End Get
		Set
			If ((Me._TurnoverCash = value)  _
						= false) Then
				Me._TurnoverCash = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TurnoverCreditCard", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property TurnoverCreditCard() As Decimal
		Get
			Return Me._TurnoverCreditCard
		End Get
		Set
			If ((Me._TurnoverCreditCard = value)  _
						= false) Then
				Me._TurnoverCreditCard = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TurnoverOther", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property TurnoverOther() As Decimal
		Get
			Return Me._TurnoverOther
		End Get
		Set
			If ((Me._TurnoverOther = value)  _
						= false) Then
				Me._TurnoverOther = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OverbakePercent100", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property OverbakePercent100() As Decimal
		Get
			Return Me._OverbakePercent100
		End Get
		Set
			If ((Me._OverbakePercent100 = value)  _
						= false) Then
				Me._OverbakePercent100 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WastagePercent100", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property WastagePercent100() As Decimal
		Get
			Return Me._WastagePercent100
		End Get
		Set
			If ((Me._WastagePercent100 = value)  _
						= false) Then
				Me._WastagePercent100 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DamagePercent100", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property DamagePercent100() As Decimal
		Get
			Return Me._DamagePercent100
		End Get
		Set
			If ((Me._DamagePercent100 = value)  _
						= false) Then
				Me._DamagePercent100 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StaffPercent100", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property StaffPercent100() As Decimal
		Get
			Return Me._StaffPercent100
		End Get
		Set
			If ((Me._StaffPercent100 = value)  _
						= false) Then
				Me._StaffPercent100 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DiscountPercent20", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property DiscountPercent20() As Decimal
		Get
			Return Me._DiscountPercent20
		End Get
		Set
			If ((Me._DiscountPercent20 = value)  _
						= false) Then
				Me._DiscountPercent20 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SamplePercent100", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property SamplePercent100() As Decimal
		Get
			Return Me._SamplePercent100
		End Get
		Set
			If ((Me._SamplePercent100 = value)  _
						= false) Then
				Me._SamplePercent100 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StockVarianceValue", DbType:="Decimal(13,2) NOT NULL")>  _
	Public Property StockVarianceValue() As Decimal
		Get
			Return Me._StockVarianceValue
		End Get
		Set
			If ((Me._StockVarianceValue = value)  _
						= false) Then
				Me._StockVarianceValue = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeName", DbType:="VarChar(51)")>  _
	Public Property EmployeeName() As String
		Get
			Return Me._EmployeeName
		End Get
		Set
			If (String.Equals(Me._EmployeeName, value) = false) Then
				Me._EmployeeName = value
			End If
		End Set
	End Property
End Class
