'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="CM")>  _
Partial Public Class SupplierViewDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.CashManagement.My.MySettings.Default.CMConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property SupplierViews() As System.Data.Linq.Table(Of SupplierView)
		Get
			Return Me.GetTable(Of SupplierView)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SupplierView")>  _
Partial Public Class SupplierView
	
	Private _RecordId As Integer
	
	Private _Description As String
	
	Private _Telephone As String
	
	Private _CellNumber As String
	
	Private _InactiveSupplier As System.Nullable(Of Integer)
	
	Private _COS As Integer
	
	Private _InactiveSupplierDescription As String
	
	Private _ExpenseType As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecordId", AutoSync:=AutoSync.Always, DbType:="Int NOT NULL IDENTITY", IsDbGenerated:=true)>  _
	Public Property RecordId() As Integer
		Get
			Return Me._RecordId
		End Get
		Set
			If ((Me._RecordId = value)  _
						= false) Then
				Me._RecordId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Description", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property Description() As String
		Get
			Return Me._Description
		End Get
		Set
			If (String.Equals(Me._Description, value) = false) Then
				Me._Description = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Telephone", DbType:="VarChar(15)")>  _
	Public Property Telephone() As String
		Get
			Return Me._Telephone
		End Get
		Set
			If (String.Equals(Me._Telephone, value) = false) Then
				Me._Telephone = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CellNumber", DbType:="VarChar(15)")>  _
	Public Property CellNumber() As String
		Get
			Return Me._CellNumber
		End Get
		Set
			If (String.Equals(Me._CellNumber, value) = false) Then
				Me._CellNumber = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InactiveSupplier", DbType:="Int")>  _
	Public Property InactiveSupplier() As System.Nullable(Of Integer)
		Get
			Return Me._InactiveSupplier
		End Get
		Set
			If (Me._InactiveSupplier.Equals(value) = false) Then
				Me._InactiveSupplier = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COS", DbType:="Int NOT NULL")>  _
	Public Property COS() As Integer
		Get
			Return Me._COS
		End Get
		Set
			If ((Me._COS = value)  _
						= false) Then
				Me._COS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InactiveSupplierDescription", DbType:="VarChar(8)")>  _
	Public Property InactiveSupplierDescription() As String
		Get
			Return Me._InactiveSupplierDescription
		End Get
		Set
			If (String.Equals(Me._InactiveSupplierDescription, value) = false) Then
				Me._InactiveSupplierDescription = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ExpenseType", DbType:="VarChar(7)")>  _
	Public Property ExpenseType() As String
		Get
			Return Me._ExpenseType
		End Get
		Set
			If (String.Equals(Me._ExpenseType, value) = false) Then
				Me._ExpenseType = value
			End If
		End Set
	End Property
End Class
